openapi: 3.1.0
info:
  version: 1.0.0
  title: Geeks team app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Geeks team app
tags:
  - name: Articles
    description: Operations about articles.
  - name: Auth
    description: Auth operations.
  - name: Authors
    description: Operations about authors.
servers:
  - url: http://localhost:3000
  # - url: https://nodejs-hw-mongodb-s5ly.onrender.com
paths:
  /articles:
    get:
      $ref: ../swagger/paths/articles/get.yaml
    post:
      $ref: ../swagger/paths/articles/post.yaml
  /articles/{id}:
    get:
      $ref: ../swagger/paths/articles/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/articles/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/articles/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refreshSession.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/requestResetPwd.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/resetPassword.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
